### ISSUE TITLE
Ошибка при выполнении запроса auth/User/getItems с подгрузкой ролей

### ISSUE THREAD

**Issue by vedorofeev** [egal/auth-service#34]
### Описание:

При попытке получить записи пользователей с ролями в сервисе auth возникает внутренняя ошибка.

### Запрос:
Method: GET
URL: https://<host>/auth/User/getItems
Body:
{
    "withs":
        ["roles"]
}

**Comment by Krishtalev** [comment]
Не удалось воспроизвести. 
{
    "action": {
        "type": "action",
        "service_name": "auth",
        "model_name": "User",
        "action_name": "getItems",
        "parameters": {
            "withs": [
                "roles"
            ]
        },
        "token": null,
        "uuid": "6f573281-f236-45f0-a5da-b8d94de6bff5"
    },
    "action_result": {
        "data": {
            "items": [
                {
                    "id": "262c0777-668e-4625-b02f-430ec80c72a3",
                    "email": "chepkasov@sputnikfund.ru",
                    "created_at": "2022-09-20T05:31:22.000000Z",
                    "updated_at": "2022-09-20T05:31:22.000000Z",
                    "roles": [
                        {
                            "id": "user",
                            "name": "User",
                            "is_default": true,
                            "pivot": {
                                "user_id": "262c0777-668e-4625-b02f-430ec80c72a3",
                                "role_id": "user"
                            }
                        }
                    ]
                }
            ]
        },
        "type": "action_result",
        "uuid": "e5c140b9-528e-4ef1-82e3-184502343c96"
    },
    "action_error": null
}
